blog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name= 'post_detail'),
    url(r'^post/new/$', views.post_new, name = 'post_new'),
    url(r'^post/(?P<pk>[0-9]+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^drafts/$', views.post_draft_list, name='post_draft_list'),
    url(r'^contactus/$', views.contact_us, name='contact_us'),
    url(r'^post/(?P<pk>[0-9]+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>[0-9]+)/remove/$', views.post_remove, name='post_remove'),
    url(r'^post/(?P<pk>[0-9]+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>[0-9]+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>[0-9]+)/remove/$', views.comment_remove, name='comment_remove'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
#Urls for our site
urlpatterns = [
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^bookmarks/', include('bookmarks.urls')),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/blog'}),
]

blog/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class Post(models.Model):
    author = models.ForeignKey('auth.user')
    title = models.CharField(max_length=200)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
       self.published_date = timezone.now()
       self.save()
    def __unicode__(self):
       return self.title
    
    def approved_comments(self):
       return self.comments.filter(approved_comment=True)
       
class Comment(models.Model):
    post =  models.ForeignKey(Post, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)
    
    
    def approve(self):
        self.approved_comment = True
        self.save()
    
    def __unicode__(self):
       return self.text

blog/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ('title','text')
        
class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ('text','author')


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment
from django.utils import timezone
from .forms import PostForm, CommentForm, ContactForm
from django.contrib.auth.decorators import login_required
from django.http import Http404,HttpResponse
from django.core.mail import send_mail

# Create your views here.

def post_list(request):
     posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
     return render(request,'blog/post_list.html',{'posts':posts})

def post_detail(request,pk):
    post = get_object_or_404(Post, pk=pk)
    '''try:
        post = Post.objects.filter(published_date__lte=timezone.now()).filter(pk=pk)
    except:
        raise Http404("Post does not published")'''  
    return render(request, 'blog/post_detail.html', {'post': post})

@login_required  
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:blog.views.post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})

#@login_required(login_url='/admin/') 
@login_required 
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:blog.views.post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

@login_required
def post_draft_list(request):
    posts = Post.objects.filter(published_date__isnull =True).order_by('create_date')
    return render(request,'blog/post_drafts.html',{'posts':posts})

@login_required     
def post_publish(request,pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blog:blog.views.post_detail', pk=pk)

@login_required         
def post_remove(request,pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('blog:blog.views.post_list')
    
def add_comment_to_post(request,pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog:blog.views.post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/add_comment_to_post.html', {'form': form})

@login_required
def comment_approve(request,pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog:blog.views.post_detail', pk=comment.post.pk) 

@login_required
def comment_remove(request,pk):
     comment = get_object_or_404(Comment, pk=pk)
     post_pk = comment.post.pk
     comment.delete()
     return redirect('blog:blog.views.post_detail', pk=post_pk)

def contact_us(request):
    if request.method == "POST":
       form = ContactForm(request.POST)
       if form.is_valid():   
             subject = form.cleaned_data['subject']
             message = form.cleaned_data['message']
             sender = form.cleaned_data['sender']
             cc_myself = form.cleaned_data['cc_myself']

             recipients = ['info@example.com']
             if cc_myself:
                 recipients.append(sender)

             #send_mail(subject, message, sender, recipients)
             #return redirect('/thanks/')
             return HttpResponse("Hi {} Thank You for Contacting Us ".format(sender))
    else:
        form = ContactForm()
    return render(request, 'blog/blog_contact.html', {'form': form})

blog/templates/blog/add_comment_to_post.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

blog/templates/blog/base.html
{% load staticfiles %}
<html>
    <head>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static "css/blog.css" %}">
        <link href="http://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
        <title>Naveens's blog</title>
    </head>
    <body>
    <div class="page-header">
        <a href="{% url 'blog:contact_us' %}" class="top-menu"><span class="glyphicon glyphicon-envelope"></a>
        {% if user.is_authenticated %}
          <a href="{% url "blog:post_new" %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
          <a href="{% url 'blog:post_draft_list' %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>
          <p class="top-menu">{{ user.username }}<small>(<a href="{% url 'django.contrib.auth.views.logout' %}">Log out</a>)</small></p>
        {% else %}
        <a href="{% url 'django.contrib.auth.views.login' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
        {% endif %}  
        <h1><a href="{% url "blog:post_list" %}">Naveen's Python Blog</a></h1>
     </div>
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>
</body>

</html>

blog/templates/blog/blog_contact.html
{% extends "blog/base.html" %}

{% block content %}
    <h1>Contact Us</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% else %}
            <a class="btn btn-default" href="{% url 'blog:post_publish' pk=post.pk %}">Publish</a>
        {% endif %}
        {% if user.is_authenticated %}
        <a class="btn btn-default" href="{% url "blog:post_edit" pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
        <a class="btn btn-default" href="{% url 'blog:post_remove' pk=post.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
        {% endif %}
        <h1>{{ post.title }}</h1>
        <p>{{ post.text|linebreaks }}</p>
    </div>
    <hr>
    <a class="btn btn-default" href="{% url 'blog:add_comment_to_post' pk=post.pk %}">Add comment</a>
    {% for comment in post.comments.all %}
    <div class="comment">
        <div class="date">{{ comment.created_date }}
        {% if not comment.approved_comment %}
            <a class="btn btn-default" href="{% url 'blog:comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
            <a class="btn btn-default" href="{% url 'blog:comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>
        {% endif %}
        </div>
        <strong>{{ comment.author }}</strong>
        <p>{{ comment.text|linebreaks }}</p>
    </div>
   {% empty %}
     <p>No comments here yet :(</p>
   {% endfor %}
{% endblock %}

blog/templates/blog/post_drafts.html
{% extends "blog/base.html" %}
{% block content %}
  {% for post in posts %}
     <div class="post">
          <div class="date">
                <p>created: {{ post.create_date }}</p>
          </div>
          <h1><a href="{% url "blog:post_detail" pk=post.pk %}">{{ post.title }}</a></h1>
          <p>{{ post.text|truncatechars:200 }}</p>
      </div>
  {% endfor %}
{% endblock content %}        

blog/templates/blog/post_edit.html
{% extends "blog/base.html" %}

{% block content %}
    <h1>New post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/base.html" %}
{% block content %}
  {% for post in posts %}
     <div class="post">
          <div class="date">
                <p>published: {{ post.published_date }}</p>
          </div>
          <h1><a href="{% url "blog:post_detail" pk=post.pk %}">{{ post.title }}</a></h1>
          <p>{{ post.text|linebreaks }}</p>
          <a href="{% url 'blog:post_detail' pk=post.pk %}">Comments: {{ post.approved_comments.count }}</a>
      </div>
  {% endfor %}
{% endblock content %}        